trigger:
- main

pool:
  vmimage: 'ubuntu-22.04'
  
steps:
- script: |
    python3.10 -m venv myenv
    source myenv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run application'